    <div class="maincontent_static">
        <h3 class="contenthead"> Datenschutzerkl&aumlrung </h3>       
        <div class="static_text1">§ 1 Zweck der Erhebung und Verwendung der Daten gemäß § 13 Abs. 1 Telemediengesetz</div>
        <div class="static_text2"><br />Wir erfassen Daten im Rahmen des Betriebs unserer Website und unserer angebotenen Dienste, beispielsweise Ihre E-Mail-Adresse, Ihr Name oder Ihre private oder geschäftliche Adresse bzw. Telefonnummer. Möglicherweise werden auch demografische Informationen erfasst, wie Postleitzahl, Alter, Geschlecht, Präferenzen, Interessen und Favoriten. Wenn Sie eine Bestellung tätigen werden weitere Informationen erfasst, z.B. Ihre Kreditkartennummer und Rechnungsadresse. <br />
    Beim erneuten Zugriff auf unsere Webseite werden Sie aufgefordert, sich mit einer E-Mail-Adresse und einem Kennwort anzumelden. Diese Daten werden als ihr „Account“ bezeichnet. <br />
    Zur weiteren Optimierung unserer Dienstleistung für Sie erfassen wir gegebenenfalls zusätzliche Daten zu Ihren Interaktionen mit unserer Website, wobei personenbezogene Daten ausgeschlossen werden. Beispielsweise werden einige Standarddaten erfasst, die Ihr Browser an die von Ihnen besuchten Websites sendet, z. B. IP-Adresse, Browsertyp und -sprache, Zugriffszeiten sowie die Adressen der Websites, durch die Sie auf diese Websites weitergeleitet wurden. Zusätzlich werden teilweise Websiteanalysetools verwendet, um Daten von Ihrem Browser abzurufen. Dazu zählen Daten wie die Website, von der aus Sie auf die Website gelangt sind, die Suchmaschine(n) und die Schlagwörter, mit denen Sie nach der betreffenden Website gesucht haben, die Seiten der Website, die Sie betrachtet haben, Ihre Browser-Add-Ons sowie die Breite und Höhe Ihres Browserfensters.</br>
    Wir verwenden ferner Technologien wie Cookies oder Webbeacons, um Informationen zu den von Ihnen angezeigten Seiten, zu den Links, auf die Sie klicken, und zu anderen Aktionen, die Sie auf den Websites oder mit den Diensten durchführen, zu sammeln. </br>
    Wenn Sie unseren Newsletter oder Werbe-E-Mails von PizzaButtler.de oder Lieferservice.de erhalten, werden möglicherweise Webbeacons, angepasste Links oder ähnliche Technologien verwendet, um festzustellen, ob Sie die E-Mail geöffnet haben und auf welche Links Sie klicken. Auf diese Weise können Ihnen E-Mails und andere Informationen bereitgestellt werden, die auf Ihre Bedürfnisse zugeschnitten sind. </br>
    Unter Umständen werden die erfassten Daten auch durch Informationen ergänzt, die von anderen Unternehmen bezogen wurden. Wir verwenden z. B. möglicherweise Dienste anderer Unternehmen, um auf der Basis Ihrer IP-Adresse ein allgemeines geografisches Gebiet abzuleiten und bestimmte Dienste an dieses geografische Gebiet anzupassen. Die Erhebung Ihrer Daten dient uns dazu, Ihnen ein nutzerfreundliches, effizientes und sicheres Internetangebot unterbreiten zu können. Wir verwenden die erhobenen und verarbeiteten personenbezogenen Daten zum Zwecke der Informationsunterbreitung für Dritte im Rahmen der Online-Bestellserivces PizzaButtler.de und Lieferservice.de sowie für die Versendung des Newsletter, sowie E-Mail-Benachrichtigungen in bestimmten Situationen, wie der Einladung zu Gruppenbestellungen, Benachrichtigung über den Status der Bestellungen etc. Dabei beachten wir selbstverständlich alle anwendbaren Datenschutzgesetze, insbesondere das Bundesdatenschutzgesetz, sowie das Telemediengesetz. Ansonsten bezweckt unsere Datenverarbeitung allgemein die Verbesserung unseres Angebots, sowie dessen Sicherheit, wobei allerdings keine personenbezogenen Daten verarbeitet werden. Diese Verarbeitung erfolgt anonym oder in pseudonymisierter Form.             <br /><br />
        </div>
        <div class="static_text1">§ 2 Art und Umfang der Erhebung und Verarbeitung persönlicher Daten</div>
        <div class="static_text2"><br />Personenbezogene Daten erheben und verarbeiten wir dann, wenn Sie sich bei uns registrieren und ein Nutzerkonto eröffnen und nachdem Sie ein solches eröffnet haben. Im Rahmen der Eröffnung des Nutzerkontos erfragen wir von Ihnen zunächst grundsätzlich folgende Daten (nachfolgend als „Bestandsdaten“ bezeichnet): <br /><br />

    Ihre E-Mail-Adresse,<br />
    Ihren vollständigen und richtigen Namen,<br />
    Ihre Telefonnummer,<br />
    Ihre Adresse (Straße und Hausnummer, Postleitzahl und Ort),<br />
    ob Sie männlich oder weiblich sind, sowie<br />
    ein Passwort, das Sie sich selbst zuweisen.<br />

    Dieses Passwort wird verschlüsselt gespeichert und ist zu keinem Zeitpunkt im Klartext sichtbar. Darüber hinaus können Sie das Nutzerprofil mit einer Vielzahl von weiteren Daten vervollständigen. Die dabei angegebenen Daten werden Teil der Bestandsdaten. <br />
    Die Bestandsdaten benötigen wir, um Ihr Nutzerkonto verwalten und bearbeiten und Sie bei Schwierigkeiten und für die oben bezeichneten E-Mail-Benachrichtigungen (die Sie jedoch jederzeit abbestellen können) erreichen zu können. <br />
    Sie haben weiterhin die Möglichkeit, sich für den Empfang eines Newsletter einzutragen. Wenn Sie sich für diese Option entschieden haben, senden wir Ihnen in angemessenen Abständen einen E-Mail-Newsletter an Ihre E-Mail-Adresse, in dem neben redaktionellen Informationen aus und über PizzaButtler.de und Lieferservice.de auch themenspezifische Werbeinhalte enthalten sein können. <br />
    Im Rahmen der Nutzung unseres Angebots verwenden wir zudem dauerhaft auf Ihrem Rechner hinterlegte Cookies (zu diesen siehe unten unter Ziffer 5). 
    Nutzungsdaten gemäß § 15 Abs. 1 Telemediengesetz.<br />
    Um uns gegen Fälle von Missbrauch und Betrug zu schützen, speichern wir für jede Nutzung unserer Webseite die IP-Adresse jedes angemeldeten (eingeloggten) Nutzers für sechs Monate. Indem Sie diese Erklärung akzeptieren, willigen Sie in diese Erhebung und Speicherung ein.<br />
    Nutzung der Webseite und Nutzungsprofile gemäß § 15 Abs. 3 Telemediengesetz.<br />
    Sie können unsere Webseiten grundsätzlich ohne die Angabe persönlicher Daten einsehen. Allerdings erstellen wir unter einem Pseudonym ein sogenanntes Nutzungsprofil, wenn Sie unsere Seite als registrierter Nutzer oder als einfacher Internetnutzer besuchen.<br />
    Danach sammeln und speichern wir in anonymisierter Form Daten zu Marketing- und Optimierungszwecken. Dies betrifft zum Beispiel Daten zu der Webseite, von der aus Sie zu unserem Angebot gelangt sind, den Namen Ihres Internet-Service-Providers, welche Webseiten Sie innerhalb unseres Internet-Angebots besucht haben sowie Datum und Dauer Ihres Besuchs. Aus diesen bereits anonymisierten Daten werden unter einem Pseudonym Nutzungsprofile erstellt. Hierzu können Cookies eingesetzt werden (zu diesen siehe unten unter Ziffer 5), die allerdings Daten ausschließlich in pseudonymer Form sammeln und speichern. Zudem speichern und verarbeiten wir in gleicher Weise in pseudonymer Form Daten über das Nutzungsverhalten der Nutzer zu Marketing und Optimierungszwecken. <br />
    In keinem Fall werden diese Daten mit anderen Daten über den Träger des Pseudonyms zusammengeführt. Das heißt zum Beispiel, dass wir nicht speichern, welches Nutzungsverhalten Sie bevorzugen, sondern nur, dass es irgendeinen Nutzer gibt, der ein solches Nutzungsverhalten hat. Es werden keine Daten gespeichert, die Rückschlüsse z.B. auf Ihr persönliches Klick- und/oder Leseverhalten zulassen. <br />
    Dieser Datensammlung und -speicherung können Sie jederzeit widersprechen.<br />
    Unsere Website kann Links zu Websites anderer, mit uns nicht verbundener Anbieter enthalten. Nach Anklicken des Links haben wir keinen Einfluss mehr auf die Verarbeitung etwaiger mit dem Anklicken des Links an den Dritten übertragener, personenbezogener Daten (wie zum Beispiel der IP-Adresse oder der URL, auf der sich der Link befindet), da das Verhalten Dritter naturgemäß unserer Kontrolle entzogen ist. Für die Verarbeitung derartiger personenbezogener Daten durch Dritte können wir daher keine Verantwortung übernehmen. <br />
    Die von uns erfassten und verwendeten persönlichen Daten werden für den Betrieb und die Verbesserung der Websites und Dienste verwendet. Die Verwendung umfasst das Bereitstellen eines effizienteren Kundenservices; die Vereinfachung der Nutzung der Websites oder Dienste, indem dafür gesorgt wird, dass dieselben Informationen nicht wiederholt eingegeben werden müssen; die Durchführung von Untersuchungen und Analysen, die auf die Optimierung von Produkten, Diensten und Technologien abzielen; und das Anzeigen von Inhalten, die auf Ihre Interessen und Präferenzen abgestimmt sind. <br />
    Wir verwenden Ihre persönlichen Daten auch, um mit Ihnen zu kommunizieren. Sie erhalten möglicherweise notwendige Servicenachrichten, wie Begrüßungsanschreiben, Zahlungserinnerungen, Informationen zu technischen Servicefragen sowie Sicherheitsmeldungen. Wir senden möglicherweise regelmäßig Newsletter an Sie, die als Teil der Dienstleistung betrachtet werden. Zusätzlich können wir Ihnen mit Ihrer Genehmigung von Zeit zu Zeit auch Produktumfragen oder Werbemailings zusenden, um Sie über andere Produkte oder Dienstleistungen zu informieren. Sie können Newsletter oder Werbe-E-Mails jederzeit abbestellen, indem Sie die im jeweiligen Newsletter bzw. in der betreffenden Werbe-E-Mail angegebenen Schritte befolgen.

            <br /><br />
        </div>
        <div class="static_text1">§ 3 Weitergabe an Dritte</div>
        <div class="static_text2"><br />Sie entscheiden selbst, welche Informationen Sie über sich neben den Pflichtangaben (siehe oben unter Ziffer 2. a)) machen wollen. Die Angabe von ergänzenden, personenbezogenen Daten erfolgt insoweit auf freiwilliger Basis und soll es Lieferservices ermöglichen, Ihnen einen besseren Service zu bieten. Diese von Ihnen freiwillig angegeben bzw. freigegebenen Daten stellen wir über die Website an den dafür vorgesehenen Stellen den Lieferservices zur Verfügung. Jenseits dessen geben wir Ihre personenbezogene Daten nur dann an Dritte weiter, wenn und soweit dies zur Durchführung des mit Ihnen bestehenden Vertragsverhältnisses notwendig ist, wir gesetzlich dazu verpflichtet sind, oder es zur Durchsetzung unserer allgemeinen Geschäftsbedingungen oder anderer mit Ihnen geschlossenen Vereinbarungen, sowie unserer Rechte und Forderungen erforderlich sein sollte.<br /><br />
        </div>
        <div class="static_text1">§ 4 Auskunft, Berichtigung, Löschung, Sperrung </div>
        <div class="static_text2"><br />Auf schriftliche Anforderung geben wir Ihnen jederzeit darüber Auskunft, welche persönlichen Daten über Sie bei uns gespeichert sind. Sie haben weiterhin jederzeit die Möglichkeit, die Daten Ihres Nutzerkontos und damit Ihre persönlichen Daten durch uns sperren oder löschen zu lassen. Hiervon ausgenommen sind ausschließlich die Daten, die wir zur Abwicklung noch ausstehender Aufgaben oder zur Durchsetzung unserer Rechte benötigen, sowie Daten, die wir nach gesetzlicher Maßgabe aufbewahren müssen.<br /><br />
        </div>
        <div class="static_text1">§ 5 Cookies und Webbeacons </div>
        <div class="static_text2"><br />Im Rahmen unserer Webseiten verwenden wir so genannte Cookies, wenn Sie bei uns ein Nutzerkonto unterhalten. Cookies sind Textdateien, die von einem Webserver auf Ihrer Festplatte gespeichert werden. Cookies enthalten Informationen, die später von einem Webserver in der Domäne gelesen werden können, in der das Cookie an Sie vergeben wurde. <br />
    Eine der Hauptaufgaben von Cookies besteht darin, Ihre Einstellungen und andere Informationen auf Ihrem Computer zu speichern, damit Sie Zeit sparen. Es besteht keine Notwendigkeit zur wiederholten Eingabe der gleichen Informationen, und personalisierte Inhalte sowie gezielte Werbung werden Ihnen bei späteren Besuchen dieser Websites angezeigt. Bei ihrem Login auf unserer Seite wird Ihre eindeutige ID-Nummer sowie die Uhrzeit Ihrer Anmeldung in einem verschlüsselten Cookie auf Ihrer Festplatte gespeichert. Dieses Cookie ermöglicht es Ihnen, auf der Website verschiedene Seiten aufzurufen, ohne sich auf jeder Seite erneut anmelden zu müssen. <br />
    Bei diesen Informationen handelt es sich insbesondere um die IP-Adresse, Login-Daten, Ihren Browsertyp und dessen Version, E-Mail-Adressen, Ihre Bestellhistorie, den URL-Clickstream (das heißt welche Webseiten Sie in welcher Reihenfolge in unserem Internetangebot besucht haben und welche Produkte Sie sich angesehen haben), das Datum und die Zeit Ihres Besuchs bei uns, sowie die Cookie-Nummer. <br />
    Der Einsatz von Cookies ermöglicht es uns zunächst, Sie zu erkennen, wenn Sie als Nutzer nach einer Session erneut unser Internetangebot besuchen. Darüber hinaus können wir durch die Cookies unser Angebot optimal nach Ihren individuellen Bedürfnissen anpassen. <br />
    Außerdem verwenden wir Cookies, um die statistische Häufigkeit der Aufrufe der verschiedenen Seiten unseres Internet-Angebots, sowie die allgemeine Navigation aufzuzeichnen.  <br />
    Wir weisen Sie jedoch darauf hin, dass Sie unser volles Angebot eventuell nicht nutzen können, wenn Sie Cookies blocken und empfehlen Ihnen daher, die Cookie-Funktionen eingeschaltet zu lassen, da Ihnen nur dann das hohe Niveau des Komforts, um das wir uns ständig bemühen, in vollem Umfang zu Gute kommt.<br />
    Sie haben die Möglichkeit, Cookies anzunehmen oder abzulehnen. Die Mehrzahl der Webbrowser nimmt Cookies automatisch an. Sie können jedoch in der Regel über die Browsereinstellungen festlegen, dass Cookies abgelehnt werden sollen. Wenn Cookies abgelehnt werden, können Sie sich möglicherweise nicht bei einzelnen Websites oder -Diensten, die von Cookies abhängig sind, anmelden oder andere interaktive Funktionen dieser Websites oder Dienste nutzen. Einige Werbeeinstellungen, die von Cookies abhängig sind, können möglicherweise nicht berücksichtigt werden.<br />
    Wenn Cookies akzeptiert werden, können Sie die akzeptierten Cookies zu einem späteren Zeitpunkt wieder löschen. In Internet Explorer 8 können Cookies beispielsweise gelöscht werden, indem Sie „Extras“ und „Browserverlauf löschen“ auswählen. Aktivieren Sie dann das Kontrollkästchen „Cookies“, und klicken Sie auf die Schaltfläche „Löschen“. Wenn Sie die Cookies löschen, werden alle Einstellungen, die von diesen Cookies gesteuert werden, einschließlich Werbeeinstellungen, gelöscht und können möglicherweise nicht mehr wiederhergestellt werden.<br />
    Unsere Webseiten enthalten möglicherweise elektronische Bilder, bekannt als Webbeacons oder Einpixel-Gifs, die dabei helfen, Cookies zuzustellen, die Anzahl der Besucher der Seiten zu ermitteln und Cobrandingdienste bereitzustellen. Wir fügen Webbeacons möglicherweise in E-Mail-Werbesendungen oder in Newsletter ein, um zu ermitteln, ob die Nachrichten geöffnet werden und zu Reaktionen führen.<br />
    Wir behalten uns vor, auch Webbeacons von Drittanbietern zu verwenden, um aggregierte Statistiken zu erstellen und den Erfolg von Werbeaktionen oder anderen Operationen auf Websites auswerten zu können.<br /><br />
        </div>
        <div class="static_text1">§ 6 Sicherheit</div>
        <div class="static_text2"><br />Wir setzen technische und organisatorische Sicherheitsmaßnahmen ein, um zu gewährleisten, dass ihre persönlichen Daten vor Verlust, falschen Veränderungen oder unberechtigten Zugriffen Dritter geschützt sind. In jedem Fall haben von unserer Seite nur berechtigte Personen Zugang zu Ihren persönlichen Daten, und dies auch nur insoweit, als es im Rahmen der oben genannten Zwecke erforderlich ist. <br />
    Die erfassten persönlichen Daten werden auf Computersystemen an streng kontrollierten Standorten gespeichert, für die nur wenige Personen Zugriffsberechtigungen besitzen. Vertrauliche persönliche Daten (wie Kreditkartennummern oder Kennwörter), die über das Internet übertragen werden, sind darüber hinaus durch Verschlüsselungstechniken wie das Secure-Socket-Layer-Protokoll (SSL-Protokoll) geschützt. <br />
    Wenn Sie zum Schutz Ihrer Konten und persönlichen Daten ein Kennwort verwenden, liegt es in Ihrer Verantwortung, das Kennwort geheim zu halten. Geben Sie diese Informationen nicht an andere Personen weiter. Wenn Sie einen Computer gemeinsam mit anderen Personen verwenden, sollten Sie sich stets abmelden, bevor Sie eine Website oder einen Dienst verlassen, um den Zugriff auf Ihre Daten durch nachfolgende Benutzer zu verhindern.<br /><br />
        </div>
        <div class="static_text1">§ 7 Identitäts- und Bonitätsprüfung bei Auswahl von Billpay-Zahlungsarten</div>
        <div class="static_text2"><br />Wenn Sie sich für eine der Zahlungsoptionen unseres Partners Billpay GmbH entscheiden, werden Sie im Bestellprozess gebeten, in die Übermittlung der für die Abwicklung der Zahlung und eine Identitäts- und Bonitätsprüfung erforderlichen Daten an Billpay einzuwilligen. Sofern Sie Ihre Einwilligung erteilen, werden Ihre Daten (Vor- und Nachname, Straße, Hausnummer, Postleitzahl, Ort, Geburtsdatum, Telefonnummer und beim Kauf per Lastschrift die angegebene Kontoverbindung) sowie die Daten im Zusammenhang mit Ihrer Bestellung an Billpay übermittelt.<br />
    Zum Zwecke der eigenen Identitäts- und Bonitätsprüfung übermittelt Billpay oder von Billpay beauftragte Partnerunternehmen Daten an Wirtschaftsauskunfteien (Auskunfteien) und erhält von diesen Auskünfte sowie ggf. Bonitätsinformationen auf Basis mathematisch-statistischer Verfahren, in deren Berechnung unter anderem Anschriftendaten einfließen. Detaillierte Informationen hierzu und zu den eingesetzten Auskunfteien sind den Datenschutzbestimmungen der Billpay GmbH zu entnehmen. <br />Des Weiteren setzt Billpay zur Aufdeckung und Prävention von Betrug ggf. Hilfsmittel Dritter ein. Mit diesen Hilfsmitteln gewonnene Daten werden ggf. bei Dritten verschlüsselt gespeichert, so dass sie lediglich von Billpay lesbar sind. Nur wenn Sie eine Zahlart unseres Kooperationspartners Billpay auswählen, werden diese Daten verwendet, ansonsten verfallen die Daten automatisch nach 30 Minuten.<br /><br />
        </div>
        <div class="static_text1">§ 8 Änderungen an diesen Datenschutzbestimmungen</div>
        <div class="static_text2"><br />Diese Datenschutzbestimmungen werden von Zeit zu Zeit aktualisiert, um Änderungen bei Diensten und Feedback von Partnern und Kunden zu berücksichtigen. Wenn Änderungen an den Bestimmungen vorgenommen wurden, können Sie das anhand des geänderten Datums unter „Letzte Aktualisierung“ am Anfang der Datenschutzbestimmungen erkennen. Bei grundlegenden Änderungen oder bei Änderungen in Bezug auf die Verwendung Ihrer persönlichen Daten durch uns wird entweder vor der Implementierung dieser Änderungen an hervorgehobener Stelle ein Hinweis angezeigt, oder Sie erhalten von uns eine direkte Benachrichtigung. Sie sollten daher diese Datenschutzbestimmungen regelmäßig überprüfen, damit Sie in Bezug auf den Schutz Ihrer persönlichen Daten durch uns“ stets aktuell informiert sind.<br /><br />
        </div>
        
        
    </div>
    <div class = "infocontent">
        <p id="infoContainerText"> Der Butler Bringts!</p>
        <div class="design">
            <div class="infoContainer_content">
                Pizza Butler GmbH<br />
                Coblitzallee 1-9<br />
                68163 Mannheim <br /><br />
                0177/9542759<br />
                info@pizza-butler.de
            </div>
        </div>
          <div class="design"> <img id="logo_uebersicht2" src="./images/butler.png" alt="Logo Pizzabutler"> </div> 

    </div>